export { createProductReducer, createProduct, createProductReset } from './createProductSlice'
export { productDetailReducer, getProductDetail, productDetailReset} from './getProductSlice'
export { deleteProductReducer, deleteProduct, deleteProductReset } from './deleteProductSlice'
export { getProductsReducer, getProducts, getProductsReset } from './productListSlice'
export { updateProductReducer, updateProduct, updateProductReset } from './updateProductSlice'
export { uploadProductImageReducer, uploadProductImageReset, uploadProductImage } from './uploadProductImageSlice'